In [29]:
import numpy as np
import scipy as sp
import matplotlib
import wave
import pandas as pd
import struct






In [2]:
wf = wave.open("test_2_48000.wav" , "r" )
buf = wf.readframes(wf.getnframes())


# バイナリデータを整数型（16bit）に変換
f = np.frombuffer(buf, dtype="int16")

In [3]:
f

array([  3765, -10078,  -4450, ...,  -6859,  -7799,  -8158], dtype=int16)

In [4]:
v = open("filter_coefficients.dba", "r")

In [5]:
v

<_io.TextIOWrapper name='filter_coefficients.dba' mode='r' encoding='UTF-8'>

In [12]:
v_arr = np.array(v.T)

In [13]:
v_arr

array([[ 0.00000000e+00, -7.09209875e-10, -7.87550842e-09,
        -3.46991182e-08, -1.01845296e-07, -2.37340741e-07,
        -4.76432977e-07, -8.61413290e-07, -1.44140397e-06,
        -2.27211079e-06, -3.41554163e-06, -4.93969270e-06,
        -6.91820333e-06, -9.42998111e-06, -1.25587987e-05,
        -1.63928644e-05, -2.10243675e-05, -2.65490015e-05,
        -3.30654660e-05, -4.06749504e-05, -4.94806011e-05,
        -5.95869740e-05, -7.10994758e-05, -8.41237953e-05,
        -9.87653283e-05, -1.15128597e-04, -1.33316668e-04,
        -1.53430571e-04, -1.75568717e-04, -1.99826330e-04,
        -2.26294877e-04, -2.55061512e-04, -2.86208537e-04,
        -3.19812872e-04, -3.55945545e-04, -3.94671200e-04,
        -4.36047632e-04, -4.80125338e-04, -5.26947100e-04,
        -5.76547595e-04, -6.28953031e-04, -6.84180817e-04,
        -7.42239266e-04, -8.03127334e-04, -8.66834388e-04,
        -9.33340018e-04, -1.00261388e-03, -1.07461559e-03,
        -1.14929463e-03, -1.22659033e-03, -1.30643188e-0

In [8]:
v = pd.read_csv("filter_coefficients.csv", header=None)

In [9]:
v

0
0    0.000000e+00
1   -7.092099e-10
2   -7.875508e-09
3   -3.469912e-08
4   -1.018453e-07
5   -2.373407e-07
6   -4.764330e-07
7   -8.614133e-07
8   -1.441404e-06
9   -2.272111e-06
10  -3.415542e-06
11  -4.939693e-06
12  -6.918203e-06
13  -9.429981e-06
14  -1.255880e-05
15  -1.639286e-05
16  -2.102437e-05
17  -2.654900e-05
18  -3.306547e-05
19  -4.067495e-05
20  -4.948060e-05
21  -5.958697e-05
22  -7.109948e-05
23  -8.412380e-05
24  -9.876533e-05
25  -1.151286e-04
26  -1.333167e-04
27  -1.534306e-04
28  -1.755687e-04
29  -1.998263e-04
..            ...
169 -1.998263e-04
170 -1.755687e-04
171 -1.534306e-04
172 -1.333167e-04
173 -1.151286e-04
174 -9.876533e-05
175 -8.412380e-05
176 -7.109948e-05
177 -5.958697e-05
178 -4.948060e-05
179 -4.067495e-05
180 -3.306547e-05
181 -2.654900e-05
182 -2.102437e-05
183 -1.639286e-05
184 -1.255880e-05
185 -9.429981e-06
186 -6.918203e-06
187 -4.939693e-06
188 -3.415542e-06
189 -2.272111e-06
190 -1.441404e-06
191 -8.614133e-07
192 -4.764330e-07
193 -2.373407e-07
194 -1.018453e-07
195 -3.469912e-08
196 -7.875508e-09
197 -7.092099e-10
198  0.000000e+00

[199 rows x 1 columns]

In [17]:
v.T

0             1             2             3             4             5    \
0  0.0 -7.092099e-10 -7.875508e-09 -3.469912e-08 -1.018453e-07 -2.373407e-07   

            6             7         8         9   ...        189       190  \
0 -4.764330e-07 -8.614133e-07 -0.000001 -0.000002 ...  -0.000002 -0.000001   

            191           192           193           194           195  \
0 -8.614133e-07 -4.764330e-07 -2.373407e-07 -1.018453e-07 -3.469912e-08   

            196           197  198  
0 -7.875508e-09 -7.092099e-10  0.0  

[1 rows x 199 columns]

In [18]:
v_arr = np.array(v.T)

In [19]:
v_arr

array([[ 0.00000000e+00, -7.09209875e-10, -7.87550842e-09,
        -3.46991182e-08, -1.01845296e-07, -2.37340741e-07,
        -4.76432977e-07, -8.61413290e-07, -1.44140397e-06,
        -2.27211079e-06, -3.41554163e-06, -4.93969270e-06,
        -6.91820333e-06, -9.42998111e-06, -1.25587987e-05,
        -1.63928644e-05, -2.10243675e-05, -2.65490015e-05,
        -3.30654660e-05, -4.06749504e-05, -4.94806011e-05,
        -5.95869740e-05, -7.10994758e-05, -8.41237953e-05,
        -9.87653283e-05, -1.15128597e-04, -1.33316668e-04,
        -1.53430571e-04, -1.75568717e-04, -1.99826330e-04,
        -2.26294877e-04, -2.55061512e-04, -2.86208537e-04,
        -3.19812872e-04, -3.55945545e-04, -3.94671200e-04,
        -4.36047632e-04, -4.80125338e-04, -5.26947100e-04,
        -5.76547595e-04, -6.28953031e-04, -6.84180817e-04,
        -7.42239266e-04, -8.03127334e-04, -8.66834388e-04,
        -9.33340018e-04, -1.00261388e-03, -1.07461559e-03,
        -1.14929463e-03, -1.22659033e-03, -1.30643188e-0

In [20]:
v_arr.shape


(1, 199)

In [24]:
v_arr = v_arr.reshape(199)

In [25]:
v_arr.shape

(199,)

In [26]:
out = np.convolve(f,v_arr,mode='full')

In [27]:
out

array([ 0.00000000e+00, -2.67017518e-06, -2.25038721e-05, ...,
        6.97795255e-05,  5.78573416e-06,  0.00000000e+00])

In [31]:
out_int = [int(x * 32767.0) for x in out]

In [28]:
out.shape

(768198,)

In [33]:
binwave = struct.pack("h" * len(out_int), *out_int)

error: short format requires (-32767 -1) <= number <= 32767

In [34]:
out_int

[0,
 0,
 0,
 -1,
 0,
 12,
 47,
 127,
 282,
 554,
 999,
 1686,
 2699,
 4140,
 6132,
 8813,
 12346,
 16914,
 22722,
 30001,
 39004,
 50009,
 63319,
 79264,
 98197,
 120498,
 146571,
 176847,
 211779,
 251845,
 297547,
 349407,
 407972,
 473804,
 547488,
 629625,
 720832,
 821739,
 932991,
 1055242,
 1189155,
 1335399,
 1494648,
 1667579,
 1854867,
 2057188,
 2275209,
 2509593,
 2760991,
 3030045,
 3317380,
 3623603,
 3949303,
 4295047,
 4661377,
 5048808,
 5457825,
 5888885,
 6342406,
 6818774,
 7318336,
 7841399,
 8388229,
 8959049,
 9554035,
 10173319,
 10816985,
 11485066,
 12177548,
 12894366,
 13635401,
 14400485,
 15189396,
 16001860,
 16837550,
 17696088,
 18577043,
 19479930,
 20404216,
 21349317,
 22314598,
 23299377,
 24302927,
 25324471,
 26363191,
 27418227,
 28488677,
 29573602,
 30672027,
 31782941,
 32905303,
 34038043,
 35180064,
 36330244,
 37487442,
 38650497,
 39818232,
 40989460,
 42162982,
 166705348,
 -285713740,
 -100127900,
 -283533781,
 -98216346,
 -281729189,
 -